[[build]]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[[build.env]]
PORT = "8080"

[deploy]
healthcheckPath = "/api/health"
healthcheckInterval = "10"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
